name: 'move-tags'
description: 'Moving tag'
author: 'snsina'
inputs:
  tag_name:
    required: true
  commit_sha:
    required: true
  token:
    required: true
outputs:
  text:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: node16
  main: index.js
